### ISSUE TITLE
Premium Version Error

### ISSUE THREAD

**Issue by RFedz007989** [Sanster/iopaint-docs#5]
Hi,

I am getting this error when done processing through Windows 1 Click Installer, not able to save Image to output directory nor able to download manually...

I am getting this below mentioned error

127.0.0.1:11711 - "POST /api/v1/save_image HTTP/1.1" 405 Method Not Allowed

Pls Assist...

Thank You

**Comment by Sanster** [comment]
Thank you for your support! I've checked out the code and found the issue, you can resolve this by configuring the Input directory.

![IMG_2532](https://github.com/Sanster/iopaint-docs/assets/3998421/7fb3c3a7-6fde-42d6-acca-a8e361cdf09f)

**Comment by RFedz007989** [comment]
> Thank you for your support! I've checked out the code and found the issue, you can resolve this by configuring the Input directory.
> 
> ![IMG_2532](https://private-user-images.githubusercontent.com/3998421/303554758-7fb3c3a7-6fde-42d6-acca-a8e361cdf09f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NTU0NTUsIm5iZiI6MTcwNzQ1NTE1NSwicGF0aCI6Ii8zOTk4NDIxLzMwMzU1NDc1OC03ZmIzYzNhNy02ZmRlLTQyZDYtYWNjYS1hOGUzNjFjZGYwOWYuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDA1MDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZmNiYzVkNmU4Nzk5NTRmNDdlMTE1YTViYmRiZTI4YjFiN2JiYjkwOThmZjFlYjUyNmI5NDAwMTZkNDM5OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lgH-klUvlNYLERGKhc5uzjh6TTrTMRwdEAf_Hc0qAVY)

Thanks I will do as you said.

But now I am getting this error which is not allowing the process to start.

(RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float
INFO:     127.0.0.1:13335 - "POST /api/v1/inpaint HTTP/1.1" 500 Internal Server Error)

Pls Fix this.
Thank You

**Comment by Sanster** [comment]
Which model are you using? I'll take a look at the code.

**Comment by RFedz007989** [comment]
> Which model are you using? I'll take a look at the code.

I am using Stable diffusion Inpainting Model (Absolutereality safetensor) which was already there by default.

**Comment by Sanster** [comment]
Hi, I have fixed this issue in `iopaint==1.1.1`. You can run `win_config.bat` to upgrade.

**Comment by RFedz007989** [comment]
> Hi, I have fixed this issue in `iopaint==1.1.1`. You can run `win_config.bat` to upgrade.

Hi, I am still getting this error

(RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float
INFO:     127.0.0.1:7269 - "POST /api/v1/inpaint HTTP/1.1" 500 Internal Server Error)

**Comment by RFedz007989** [comment]
> > Hi, I have fixed this issue in `iopaint==1.1.1`. You can run `win_config.bat` to upgrade.
> 
> Hi, I am still getting this error
> 
> (RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float INFO: 127.0.0.1:7269 - "POST /api/v1/inpaint HTTP/1.1" 500 Internal Server Error)

Whenever I try to load SDXL models it gives me error (Failed to load Code 500 Internal Server Error)

**Comment by Sanster** [comment]
1. Can you please upload the `installer_config.json` configuration file to help me locate the issue?

2. When an error occurs, there will be more detailed error messages in the command line. Could you please take a screenshot for me?
<img width="1227" alt="image" src="https://github.com/Sanster/iopaint-docs/assets/3998421/11ae600d-aea1-4f9c-8f29-8753c805fbdd">

**Comment by RFedz007989** [comment]
> 1. Can you please upload the `installer_config.json` configuration file to help me locate the issue?
> 2. When an error occurs, there will be more detailed error messages in the command line. Could you please take a screenshot for me?
> 
> <img alt="image" width="1227" src="https://private-user-images.githubusercontent.com/3998421/303822689-11ae600d-aea1-4f9c-8f29-8753c805fbdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTA4NjUsIm5iZiI6MTcwNzU1MDU2NSwicGF0aCI6Ii8zOTk4NDIxLzMwMzgyMjY4OS0xMWFlNjAwZC1hZWExLTRmOWMtOGYyOS04NzUzYzgwNWZiZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTBUMDczNjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFjYTBiNTVlNTI3OGY2ODk5MjhkYTczNmQ4MTRjZWQwMzhlMmQwZjRlMThjYTYzOWFlNDYwZGI2MTM2ZjZmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4D9AmjoFbiHgXaPvbI60dyJBhfnCn_ttj1OQciaIZV0">

> 1. Can you please upload the `installer_config.json` configuration file to help me locate the issue?
> 2. When an error occurs, there will be more detailed error messages in the command line. Could you please take a screenshot for me?
> 
> <img alt="image" width="1227" src="https://private-user-images.githubusercontent.com/3998421/303822689-11ae600d-aea1-4f9c-8f29-8753c805fbdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NTA4NjUsIm5iZiI6MTcwNzU1MDU2NSwicGF0aCI6Ii8zOTk4NDIxLzMwMzgyMjY4OS0xMWFlNjAwZC1hZWExLTRmOWMtOGYyOS04NzUzYzgwNWZiZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTBUMDczNjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTFjYTBiNTVlNTI3OGY2ODk5MjhkYTczNmQ4MTRjZWQwMzhlMmQwZjRlMThjYTYzOWFlNDYwZGI2MTM2ZjZmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4D9AmjoFbiHgXaPvbI60dyJBhfnCn_ttj1OQciaIZV0">

OK I will

**Comment by RFedz007989** [comment]
[installer_config.json](https://github.com/Sanster/iopaint-docs/files/14228542/installer_config.json)

Pls check

**Comment by RFedz007989** [comment]
Hi,

I uploaded 2 screenshots, as the length of it wasn't fitting in one screenshot.
This error I encountered while loading SDXL Model. Hope this will help to fix the issue...
![01](https://github.com/Sanster/iopaint-docs/assets/158298313/057667ac-7427-4f18-9bc2-a58eb4ae6916)
![02](https://github.com/Sanster/iopaint-docs/assets/158298313/1cb48d9f-90dc-4472-b76b-21c18e78b891)


Thank You

**Comment by Sanster** [comment]
> RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float

I reproduced this error when enabling ControlNet (no problem when it was disabled). It has been fixed in `iopaint==1.1.2`.


> load single file(ckpt/safetensors) SDXL Model  error

This issue is likely caused by not placing the sdxl file into the corresponding directory. You need to place the sdxl model into the `stable_diffusion_xl` directory in order for IOPaint to distinguish between sd and sdxl files.

```
- some cache_dir 
  |- stable_diffusion
      ├── sd-v1-5-inpainting.ckpt
      ├── sd-v1-5-inpainting.safetensors
      └── v1-5-pruned-emaonly.safetensors
  |- stable_diffusion_xl
      ├── sd_xl_base_1.0.safetensors
      └── sd_xl_base_1.0_inpainting_0.1.safetensors
```

**Comment by RFedz007989** [comment]
> > RuntimeError: mat1 and mat2 must have the same dtype, but got Half and Float
> 
> I reproduced this error when enabling ControlNet (no problem when it was disabled). It has been fixed in `iopaint==1.1.2`.
> 
> > load single file(ckpt/safetensors) SDXL Model  error
> 
> This issue is likely caused by not placing the sdxl file into the corresponding directory. You need to place the sdxl model into the `stable_diffusion_xl` directory in order for IOPaint to distinguish between sd and sdxl files.
> 
> ```
> - some cache_dir 
>   |- stable_diffusion
>       ├── sd-v1-5-inpainting.ckpt
>       ├── sd-v1-5-inpainting.safetensors
>       └── v1-5-pruned-emaonly.safetensors
>   |- stable_diffusion_xl
>       ├── sd_xl_base_1.0.safetensors
>       └── sd_xl_base_1.0_inpainting_0.1.safetensors
> ```

Thanks a lot. It's working just fine now without any bugs
Thanks for fixing this asap
If I get any issues I will for sure notify you.
Have a Wonderful Weekend :)

Thank You

**Comment by RFedz007989** [comment]
Hi,

I tried Segment Anything & just wanted to say that Left Positive Click (Green) is working Good, but when comes to right negative click (Red) doesn't work means when I right click for negative it shows Red point color, but when I click it reflects as Positive infact I clicked on Negative. can you pls check this.

I short left positive click is working fine, but right negative click is not working...

Thank You

**Comment by Sanster** [comment]
- Can you upload a test image for me to try?
- It might also be a problem with the SAM model's performance. You could try using a larger model. The default model used by IOPaint is `vit_b`. The larger the model, the better the performance. The size of the models is as follows: `mobile_sam < vit_b < vit_l < vit_h`.

**Comment by RFedz007989** [comment]
> * Can you upload a test image for me to try?
> * It might also be a problem with the SAM model's performance. You could try using a larger model. The default model used by IOPaint is `vit_b`. The larger the model, the better the performance. The size of the models is as follows: `mobile_sam < vit_b < vit_l < vit_h`.

Thanks
I prefer using this **vit_h**
I uploaded an Image. Pls try
If possible pls record  a very small clip when you are doing Negative point (Red)
Thank You

**Comment by Sanster** [comment]
I have added several new SAM models. You can try them out and see how they work.
  - sam_hq_vit_b
  - sam_hq_vit_l
  - sam_hq_vit_h 

Here is a video demonstration of using Negative Point

https://github.com/Sanster/iopaint-docs/assets/3998421/03a6b61d-67ef-4d20-9bf6-2ced958a5685

**Comment by RFedz007989** [comment]
> I have added several new SAM models. You can try them out and see how they work.
> 
> * sam_hq_vit_b
> * sam_hq_vit_l
> * sam_hq_vit_h
> 
> Here is a video demonstration of using Negative Point
> 
>  sam.mp4

Thank You very much for demo video of how to use negative point. It's working good now.

**Comment by RFedz007989** [comment]
Can you pls tell how to use Instruct2pix, as I am not able to locate in IOpaint tool.
Thank You
